<a href="https://colab.research.google.com/github/mmunibaferoz-ctrl/Numpy/blob/main/NUMPY_task_%2B_hands_on.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 1 - Create Array and Find Sum, Average, Max, Min

# 1. Create this array
arr = [20, 30, 40, 50, 60]
print("Array:", arr)

# 2. Find Sum
total_sum = sum(arr)
print("Sum:", total_sum)

# 3. Find Average
average = total_sum / len(arr)
print("Average:", average)

# 4. Find Maximum
maximum = max(arr)
print("Maximum:", maximum)

# 5. Find Minimum
minimum = min(arr)
print("Minimum:", minimum)

Array: [20, 30, 40, 50, 60]
Sum: 200
Average: 40.0
Maximum: 60
Minimum: 20


In [ ]:
import numpy as np

# Task 2 - Create NumPy array and filter marks
marks = np.array([45, 70, 90, 90, 30, 80, 70])

# Filter marks >= 50
print(marks[marks >= 50])

[70 90 90 80 70]


In [ ]:
# Task 3 reshape array into 2 rows
import numpy as np

# create this array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2 rows (and 3 columns)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Task 4 - Generate 10 random marks between 40 and 100
import random
import numpy as np

# 1. Generate 10 random marks between 40 and 100
marks = np.random.randint(40, 101, 10)

print(f"Random Marks: {marks}")

# 2. Find Average
average = sum(marks) / len(marks)
print(f"Average: {average:.2f}")

# 3. Find Highest marks
highest = max(marks)
print(f"Highest Marks: {highest}")

# 4. Find Lowest marks
lowest = min(marks)
print(f"Lowest Marks: {lowest}")

Random Marks: [85 79 40 82 52 75 95 47 91 73]
Average: 71.90
Highest Marks: 95
Lowest Marks: 40


In [ ]:
# Task 5 - Find Passed and Failed marks
import numpy as np

# 1. Create this marks array
marks = np.array([40, 70, 99, 55, 80, 22, 50, 58])
passing_marks = 50

print(f"All Marks: {marks}")
print(f"Passing Marks: {passing_marks}\n")

# 2. Passed marks (>= 50)
passed_marks = marks[marks >= passing_marks]
print(f"Passed Marks: {passed_marks}")

# 3. Failed marks (< 50)
failed_marks = marks[marks < passing_marks]
print(f"Failed Marks: {failed_marks}")

# 4. Number of passed students
num_passed = len(passed_marks)
print(f"Number of Passed Students: {num_passed}")

# 5. Number of failed students
num_failed = len(failed_marks)
print(f"Number of Failed Students: {num_failed}")

All Marks: [40 70 99 55 80 22 50 58]
Passing Marks: 50

Passed Marks: [70 99 55 80 50 58]
Failed Marks: [40 22]
Number of Passed Students: 6
Number of Failed Students: 2


In [ ]:
import numpy as np


# 1. Array
my_array = np.array([20, 30, 40, 50, 70])

# 2. Average
print(np.mean(my_array)) # Output: 30.0

# 3. Maximum
print(np.max(my_array))  # Output: 50

# 4. Minimum
print(np.min(my_array))  # Output: 10

# 5. Sum
print(np.sum(my_array))  # Output: 150

42.0
70
20
210


In [ ]:
marks_list = [90, 70, 80, 50]
print("Marks List:", marks_list)


import numpy as np

marks_array = np.array([70, 80, 90, 60])
print("NumPy Array:", marks_array)

print("Average:", np.mean(marks_array))
print("Sum:", np.sum(marks_array))
print("Max:", np.max(marks_array))

Marks List: [90, 70, 80, 50]
NumPy Array: [70 80 90 60]
Average: 75.0
Sum: 300
Max: 90


In [ ]:
import numpy as np

#
numbers = np.array([10, 20, 30, 40])

print(numbers)

[10 20 30 40]


In [ ]:
import numpy as np

# 2D Array
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

print(marks)

[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
import numpy as np

data = np.array([
    [20, 40, 30],
    [30, 20, 40]
])

print(data)

[[20 40 30]
 [30 20 40]]


In [ ]:
print(data.ndim)#

2


In [ ]:
print  (data.shape)#

(2, 3)


In [ ]:
print (data.size)#

6


In [ ]:
print(data.dtype)#

int64


In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])

10


In [ ]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

In [ ]:
print(marks[0, 1])

80


In [ ]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1:4])

[20 30 40]


In [ ]:
numbers = np.array([15, 45, 30, 30])

In [ ]:
print(numbers + 5)

[20 50 35 35]


In [ ]:
print(numbers * 2)

[30 90 60 60]


In [ ]:
print(numbers - 5)

[10 40 25 25]


In [ ]:
print(numbers / 2)

[ 7.5 22.5 15.  15. ]


In [ ]:
a = np.array([10, 20, 30])

b = np.array([1, 2, 3])
print(a + b)

[11 22 33]


In [ ]:
print(a * b)

[10 40 90]


In [ ]:
marks = np.array([70, 85, 60, 95, 80])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.median(marks))
print(np.std(marks))

390
78.0
95
60
80.0
12.083045973594572


In [ ]:
# Condition in NUMPY
marks = np.array([30, 50, 80, 45, 90, 20])

print(marks >= 50)

[False  True  True False  True False]


In [ ]:
# Filtering data
marks = np.array([30, 50, 80, 45, 90, 20])

passed = marks[marks >= 50]

print(passed)

[50 80 90]


In [ ]:
failed = marks[marks < 50]

print(failed)

[30 45 20]


In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])
reshaped_numbers = numbers.reshape(2, 3)
print(reshaped_numbers)
new_array = numbers.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Flatten
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.flatten())

[1 2 3 4 5 6]


In [ ]:

print(np.zeros(5))
print(np.ones(5))
print(np.arange(1, 12))
print(np.arange(0, 11, 2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10]


In [ ]:
# random number
marks = np.random.randint(40, 100, 10)

print(marks)

[56 81 91 63 96 59 63 95 79 89]
