<a href="https://colab.research.google.com/github/mmunibaferoz-ctrl/Numpy/blob/main/NUMPY_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#numpy task 1 to 5
#task 1
marks = np.array([10,20,30,40,50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

150
30.0
50
10


In [ ]:
#task2
marks = np.array([45,80,30,90,80,55,20])
del print # Restore the built-in print function
print(marks >= 50)

[False  True False  True  True  True False]


In [ ]:
#task 3
numbers = np.array([1,2,3,4,5,6])
new_array = numbers.reshape(2, 3)

print(new_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Task 4
marks = np.random.randint(40, 101, 10)

print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Marks: [95 48 52 40 78 65 50 66 71 72]
Average: 63.7
Highest: 95
Lowest: 40


In [ ]:
#task 5
import numpy as np

marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed_marks = marks[marks >= 50]
failed_marks = marks[marks < 50]

print("Passed marks:", passed_marks)
print("Failed marks:", failed_marks)
print("Number of passed:", len(passed_marks))
print("Number of failed:", len(failed_marks))

Passed marks: [67 89 90 70 58]
Failed marks: [35 45 22]
Number of passed: 5
Number of failed: 3


In [ ]:
#Handzone
#Import NumPy
import numpy as np
#np.array()
#np.mean()
#np.max()

In [ ]:
#Python List vs NumPy Array

marks = [50, 90, 80, 30]
import numpy as np

marks = np.array([50, 90, 80, 30])

print(marks)

[50 90 80 30]


In [ ]:
#Creating NumPy Arrays
numbers = np.array([50, 60, 30, 40])

print(numbers)

[50 60 30 40]


In [ ]:
#Two-Dimensional array

marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

print(marks)

[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
#import array properties
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)

2
(2, 3)
6
int64


In [ ]:
#Indexing
numbers = np.array([100,200,300,500,600])
print(numbers[4])
print(numbers[3])

#negative indexing

print(numbers[-5])

600
500
100


In [ ]:
#Indexing in a 2D Array
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])
print(marks[0, 1])

80


In [ ]:
#slicing
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[1:4])

[20 30 40]


In [ ]:
#Vectorized Operations
numbers = np.array([20,30,90,60])
print(numbers + 15)
print(numbers * 2)
print(numbers - 10)
print(numbers / 5)

[ 35  45 105  75]
[ 40  60 180 120]
[10 20 80 50]
[ 4.  6. 18. 12.]


In [ ]:
#Operations Between Two arrays
a = np.array([40, 50, 70])
b = np.array([1, 5, 10])
print(a + b)
print(a - b)
print(a * b)
print(a / b )

[41 55 80]
[39 45 60]
[ 40 250 700]
[40. 10.  7.]


In [ ]:
#Mathematical Functions
numbers = np.array([4, 9, 16, 25])

print(np.sqrt(numbers))
numbers = np.array([2, 3, 4])

print(np.power(numbers, 2))

[2. 3. 4. 5.]
[ 4  9 16]


In [ ]:
#Absolute
numbers = np.array([-10,20,30])
print(np.abs(numbers))

[10 20 30]


In [ ]:
#Round
numbers = np.array([6.2, 4.5, 7.8, 9.3])
print(np.round(numbers))

[6. 4. 8. 9.]


In [ ]:
#Aggregation Functions
marks = np.array([10, 20, 30, 40])
print(np.sum(marks))
print(np.max(marks))
print(np.min(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))

100
40
10
25.0
25.0
11.180339887498949


In [ ]:
#Conditions in NumPy
marks = np.array([30, 50, 80, 45, 90, 20])

print(marks >= 50)

[False  True  True False  True False]


In [ ]:
#Filtering Data
marks = np.array([30, 50, 80, 45, 90, 20])

passed = marks[marks >= 50]

print(passed)

[50 80 90]


In [ ]:
failed = marks[marks < 50]
print(failed)

[30 45 20]


In [ ]:
#Reshape
numbers = np.array([1, 2, 3, 4, 5, 6])
print(numbers)
new_array = numbers.reshape(2, 3)

print(new_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Flatten
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.flatten())

[1 2 3 4 5 6]


In [ ]:
#useful NumPy Functions
print(np.zeros(5))
print(np.ones(5))

print(np.arange(1, 11))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Random Numbers
marks = np.random.randint([10,20,30,40])
print(marks)

[ 5  7 14  4]
